name: Deploy to AutoDL

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.AUTODL_SSH_KEY }}

    - name: Deploy to AutoDL server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AUTODL_USER }}@${{ secrets.AUTODL_HOST }} << 'EOF'
          # 在服务器上运行的命令
          cd /path/to/your/project || exit 1
          git pull origin main
          docker-compose down
          docker-compose up -d --build
        EOF
