name: Deploy to AutoDL with Password

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to AutoDL server using password
      env:
        AUTODL_PASSWORD: ${{ secrets.AUTODL_PASSWORD }}
      run: |
        sshpass -p "$AUTODL_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.AUTODL_USER }}@${{ secrets.AUTODL_HOST }} << 'EOF'
          # 在服务器上运行的命令
          cd /path/to/your/project || exit 1
          git pull origin main
          docker-compose down
          docker-compose up -d --build
        EOF
